name: Build

on:
  push:
    branches: ["*"]
    tags-ignore: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install .NET Sdk
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Do build
        run: |
          dotnet build -C Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: "nupkgs"
